### ISSUE TITLE
Serial2 works only upto version 1.0.6 Arduino ESP32

### ISSUE THREAD

**Issue by asking23** [G6EJD/ESP32-Using-Hardware-Serial-Ports#4]
I had working Serial2 on GPIO 16 / 17.

But due to SD card library requirement when i upgrade ESP32 Core version 1.0.6 to 2.0.x it does'nt work any more.

any idea what could be done to restore the Seria2 on GPIO 16/17 ?

**Comment by G6EJD** [comment]
The answer will be in the SD library files.
I would try the code or a simple test using serial2 to make sure the new compiler it wi, if so, then it’s definitely the SD library.
Inspect the source code of the SD library and see what pins they are using. 
you may have to select two new pins for the Serial2 function.

**Comment by asking23** [comment]
SD Card library is usin SPI Function MISO/MOSIC/CLK which are completely different from GPIO 16/17.

Its Arduino ESP Core Version 1.0.5/1.0.6 till then Serial2 works fine on 16/17, But SD Library has some compilation error.

In Arduino ESP Core Version 2.0.x Serial2 Stopped working on 16/17 and SD library works fine.

**Comment by G6EJD** [comment]
SPI2 uses pin 17 for clk but 16/17 can also be affected by board type and which pins the compiler is allocating.
